import { Bot, ChevronDown, ChevronRight, FolderGit2, FolderOpen, Plus, Settings2, Sparkles, Trash2 } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useAppStore } from '../store'
export function Sidebar(): React.JSX.Element {
  const state = useAppStore(); const [selectedProjectId, setSelectedProjectId] = useState<string | null>(null)
  const [collapsedProjectIds, setCollapsedProjectIds] = useState<string[]>(() => {
    try { return JSON.parse(window.localStorage.getItem('agentdesk:collapsed-projects') ?? '[]') as string[] } catch { return [] }
  })
  const projects = useMemo(() => state.workspaces, [state.workspaces]); const standalone = state.tasks.filter((task) => task.scope === 'standalone')
  useEffect(() => { window.localStorage.setItem('agentdesk:collapsed-projects', JSON.stringify(collapsedProjectIds)) }, [collapsedProjectIds])
  const toggleProject = (id: string): void => setCollapsedProjectIds((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id])
  const removeProject = (id: string): void => { if (window.confirm('从 AgentDesk 中移除此项目？磁盘文件不会被删除，关联任务将转为普通任务。')) void state.removeWorkspace(id) }
  const removeTask = (id: string): void => { if (window.confirm('删除此任务及其本地运行记录？')) void state.deleteTask(id) }
  return <aside className="sidebar"><div className="brand"><div className="brand-icon">A</div><strong>AgentDesk</strong></div><div className="sidebar-actions"><button className="primary-nav" onClick={() => void state.createStandaloneTask()}><Plus size={17} />新建任务</button><button onClick={() => void state.chooseWorkspace()}><FolderOpen size={16} />新建项目</button><button onClick={() => state.setAppDrawer('lab')}><Sparkles size={16} />SDK 实验室</button><button onClick={() => state.setAppDrawer('providers')}><Settings2 size={16} />模型设置</button></div>
    <div className="sidebar-scroll"><section className="nav-section"><div className="nav-heading">项目 <button onClick={() => void state.chooseWorkspace()} aria-label="新建项目"><Plus size={14} /></button></div>{projects.length === 0 && <div className="nav-empty">还没有项目</div>}{projects.map((project) => { const projectTasks = state.tasks.filter((task) => task.workspaceId === project.id); const selected = selectedProjectId === project.id; const collapsed = collapsedProjectIds.includes(project.id); return <div className={`project-tree ${collapsed ? 'collapsed' : ''}`} key={project.id}><div className={`project-row ${selected ? 'selected' : ''}`} onClick={() => setSelectedProjectId(project.id)}><button className="project-toggle" title={collapsed ? '展开项目任务' : '收起项目任务'} aria-label={collapsed ? '展开项目任务' : '收起项目任务'} aria-expanded={!collapsed} onClick={(event) => { event.stopPropagation(); toggleProject(project.id) }}>{collapsed ? <ChevronRight size={14} /> : <ChevronDown size={14} />}</button>{project.isGit ? <FolderGit2 size={15} /> : <FolderOpen size={15} />}<span title={project.path}>{project.name}</span><em>{projectTasks.length}</em><button title="删除项目" onClick={(event) => { event.stopPropagation(); removeProject(project.id) }}><Trash2 size={13} /></button></div>{!collapsed && <div className="project-children">{selected && <button className="project-new-task" onClick={() => void state.createTask(project.id)}><Plus size={13} />在此项目中新建任务</button>}{projectTasks.map((task) => <TaskRow key={task.id} nested task={task} active={state.activeTaskId === task.id} onSelect={() => void state.selectTask(task.id)} onDelete={() => removeTask(task.id)} />)}</div>}</div>})}</section><section className="nav-section standalone-section"><div className="nav-heading">任务</div>{standalone.length === 0 ? <div className="nav-empty">普通任务会显示在这里</div> : standalone.map((task) => <TaskRow key={task.id} task={task} active={state.activeTaskId === task.id} onSelect={() => void state.selectTask(task.id)} onDelete={() => removeTask(task.id)} />)}</section></div><div className="sidebar-footer"><Bot size={15} /><span>Claude Agent SDK</span><i>本地</i></div>
  </aside>
}
function TaskRow({ task, active, nested = false, onSelect, onDelete }: { task: { id: string; title: string; status: string }; active: boolean; nested?: boolean; onSelect: () => void; onDelete: () => void }): React.JSX.Element { return <div className={`task-row ${nested ? 'nested' : ''} ${active ? 'active' : ''}`}><button className="task-select" onClick={onSelect}><i className={task.status} /><span><strong>{task.title}</strong></span></button><button className="task-delete" title="删除任务" onClick={onDelete}><Trash2 size={13} /></button></div> }
